import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { contractData } from '../scripts/agents-mother/contract.mjs';
import { researchMarkdown } from '../scripts/agents-mother/index.mjs';
import { patternPackMarkdown } from '../scripts/agents-mother/pattern-research.mjs';
import { researchGateDecisionForReport } from '../scripts/agents-mother/research-gate.mjs';
import { createOutcomeSpec, validateOutcomeSpecText, approveOutcomeSpec, compileOutcomeSpec } from '../scripts/agents-mother/outcome-spec.mjs';
import { FunctionBuildExecutor } from '../scripts/agents-mother/build-executors.mjs';
import { runDeliveryLoop, acceptDelivery } from '../scripts/agents-mother/delivery-loop.mjs';
import { prepareAuthoredHandoff } from '../scripts/agents-mother/authored-handoff.mjs';
const git=(cwd,args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:'pipe'}).trim();

test('clean headless path passes its research gate, separate Outcome approval, independent Trials and handoff without overrides', async t => {
 const parent=realpathSync(mkdtempSync(path.join(os.tmpdir(),'pritha-clean-cli-')));t.after(()=>rmSync(parent,{recursive:true,force:true}));
 const root=path.join(parent,'mother'),stateRoot=path.join(parent,'state'),agentParent=path.join(parent,'children'),project=path.join(agentParent,'sum-cli');
 const contracts=path.join(stateRoot,'agents/contracts'),researchDir=path.join(stateRoot,'agents/research');
 for(const folder of [root,agentParent,contracts,researchDir])mkdirSync(folder,{recursive:true});
 const previousState=process.env.PRITHA_STATE_ROOT;process.env.PRITHA_STATE_ROOT=stateRoot;t.after(()=>{if(previousState===undefined)delete process.env.PRITHA_STATE_ROOT;else process.env.PRITHA_STATE_ROOT=previousState;});
 const options={root,stateRoot,agentParent,projectPath:project};
 const contract=path.join(contracts,'sum-contract.md');
 let source=readFileSync('tests/fixtures/contracts/valid-agent-contract.md','utf8').replace('status: accepted','status: accepted\ncontract_schema_version: 2\nagent_id: synthetic-sum\nagent_kind: one-shot-cli');
 for(const [field,value] of Object.entries({'Agent name':'Synthetic Sum','Primary mission':'Return the sum of two finite numbers as JSON','Success criteria':'Correct sums and invalid-input exit code 64','Target folder':project,'Runtime family':'cli','Primary interface':'CLI','Secondary interfaces':'none','Service mode':'none','Autostart':'disabled','Proactive mode':'none'}))source=source.replace(new RegExp(`^- ${field}:.*$`,'m'),`- ${field}: ${value}`);
 source=source.replace(/(### V1 core functions\n)[\s\S]*?(?=\n### )/,'$1\n- Return correct JSON sums and reject invalid input.\n');writeFileSync(contract,source);
 const data=contractData(contract,{root});
 const memoryResults=[{type:'standard',status:'accepted',path:'04_standards/agent-creation-harness.md',title:'Synthetic curated memory fixture',snippet:'Use a deterministic CLI with independent tests and explicit acceptance.'}];
 const domains={agentBuildingKnowledge:[],prithaSelf:[],childAgents:[]};
 const pack=patternPackMarkdown(data,{memoryResults,domainResults:domains,query:'deterministic CLI verification'},{artifactId:'synthetic-patterns'});
 const packFile=path.join(researchDir,'synthetic-patterns.md');writeFileSync(packFile,pack.text);
 const skills={policy:{skillNeeds:'none',allowedSkillSources:'local',skillInstallMode:'none',skillMutationPolicy:'none'},installed:[],candidates:[],blocked:[]};
 const report=researchMarkdown(data,memoryResults,domains,[],skills,{externalResearchTopics:[],patternPack:{...pack,relPath:path.relative(root,packFile)}});
 const gate=researchGateDecisionForReport(data,report);assert.equal(gate.ok,true,JSON.stringify(gate.reasons));
 writeFileSync(path.join(researchDir,'synthetic-research.md'),report);
 const env={...process.env,TECHSCOPE_ROOT:root,PRITHA_STATE_ROOT:stateRoot,PRITHA_AGENT_PARENT:agentParent};
 const scaffold=execFileSync(process.execPath,['scripts/pritha.mjs','scaffold',contract],{encoding:'utf8',env,timeout:30000});assert.doesNotMatch(scaffold,/experimental scaffold overrides/);
 assert.equal(existsSync(path.join(project,'operations/manifest.json')),false);
 mkdirSync(path.join(project,'verification'));
 const verifier=`import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';\nfor(const [a,b,expected] of [['2','3',5],['-3','1',-2],['0','0',0]]){const r=spawnSync(process.execPath,['scripts/agent-cli.mjs',a,b],{encoding:'utf8',timeout:2000});assert.equal(r.status,0);assert.deepEqual(JSON.parse(r.stdout),{sum:expected});}\nconst bad=spawnSync(process.execPath,['scripts/agent-cli.mjs','bad','1'],{encoding:'utf8',timeout:2000});assert.equal(bad.status,64);console.log('sum verified');\n`;
 writeFileSync(path.join(project,'verification/check.mjs'),verifier);
 const spec=createOutcomeSpec(contract,options).path;let draft=readFileSync(spec,'utf8');
 const covers=validateOutcomeSpecText(draft,options).coverage.map(row=>`- Covers: ${row.id}`).join('\n');
 const sha=createHash('sha256').update(verifier).digest('hex');
 draft=draft.replace(/## Trials\n[\s\S]*?(?=## Demo script)/,`## Trials\n\n### Trial: sums\n\n- Statement: CLI returns correct sums and rejects invalid numbers.\n- Kind: automated\n${covers}\n- Isolation: none\n- When argv: ["node", "verification/check.mjs"]\n- When cwd: .\n- Then exit code: 0\n- Then stdout contains: sum verified\n- Product target: scripts/agent-cli.mjs\n- Verifier input: verification/check.mjs :: sha256:${sha} :: host-reviewed:synthetic-sum-v1\n- Timeout ms: 10000\n\n`);
 draft=draft.replace(/## Demo script\n[\s\S]*$/,'## Demo script\n\n1. Run `node scripts/agent-cli.mjs 2 3`; expect `{"sum":5}` and exit 0.\n2. Run `node scripts/agent-cli.mjs bad 1`; expect exit 64.\n');writeFileSync(spec,draft);
 git(project,['add','.']);git(project,['commit','-m','review independent verifier']);approveOutcomeSpec(spec,{...options,approvedBy:'user'});
 const compiled=compileOutcomeSpec(spec,{...options,runId:'synthetic-clean-cli'});let calls=0;
 const executor=new FunctionBuildExecutor(async({worktree})=>{calls++;writeFileSync(path.join(worktree,'scripts/agent-cli.mjs'),`const [a,b]=process.argv.slice(2).map(Number);if(!Number.isFinite(a)||!Number.isFinite(b)){console.error('Invalid input');process.exitCode=64;}else console.log(JSON.stringify({sum:a+b}));\n`);return{summary:'Synthetic deterministic executor fixture; no model',changed_files:['scripts/agent-cli.mjs']};});
 const result=await runDeliveryLoop({...options,...compiled,buildExecutor:executor,trialBackend:'local',reportDir:false});assert.equal(result.state.status,'verified',JSON.stringify(result.state.blockers));assert.equal(calls,1);
 // This approval is synthetic test input, never a claim about user acceptance.
 git(project,['merge','--ff-only',result.worktree.branch]);
 const accepted=acceptDelivery(compiled.runId,{...options,acceptedBy:'user'});assert.equal(accepted.state.status,'accepted');
 const handoff=prepareAuthoredHandoff(project,options);assert.match(readFileSync(handoff.reportPath,'utf8'),/2 3/);assert.equal(handoff.readiness.verification.status,'verified');assert.equal(handoff.readiness.acceptance.status,'accepted');
 assert.equal(git(project,['status','--porcelain']),'');
});
