#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { resolveTechscopeRoot } from "./lib/paths.mjs";

const ROOT = resolveTechscopeRoot();
const DEFAULT_STATE_PATH = path.join(ROOT, ".techscope-setup.json");
const DEFAULT_ENV_PATH = path.join(ROOT, ".env.local");
const SETUP_VERSION = 1;

export function routeTriggerPhrase(text) {
  const value = String(text || "").trim().toLowerCase();
  if (!value) return null;
  if (/(^|\s)(запусти проект|setup|first run|bootstrap|start)(\s|$)/iu.test(value)) {
    return {
      id: "first-run-setup",
      workflow: "07_workflows/first-run-setup.md",
      command: "node scripts/setup.mjs",
    };
  }
  if (/(^|\s)(проверь проект|self test|health)(\s|$)/iu.test(value)) {
    return {
      id: "self-test",
      workflow: "07_workflows/self-test.md",
      command: "node scripts/self-test.mjs",
    };
  }
  if (/(^|\s)(создай агента|new agent|interview)(\s|$)/iu.test(value)) {
    return {
      id: "pritha-interview",
      workflow: "07_workflows/agents-mother.md",
      command: "node scripts/pritha.mjs interview",
    };
  }
  return null;
}

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = argv[i + 1];
      if (!next || next.startsWith("--")) {
        out[key] = true;
      } else {
        out[key] = next;
        i += 1;
      }
    } else {
      out._.push(arg);
    }
  }
  return out;
}

function readJsonIfExists(filePath) {
  if (!existsSync(filePath)) return null;
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function safeRelative(filePath) {
  const rel = path.relative(ROOT, filePath);
  return rel.startsWith("..") ? filePath : rel;
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    timeout: options.timeoutMs || 180000,
    env: { ...process.env, TECHSCOPE_ROOT: ROOT },
  });
  return {
    ok: result.status === 0,
    status: result.status ?? 1,
    stdout: String(result.stdout || "").trim(),
    stderr: String(result.stderr || "").trim(),
  };
}

function mask(value) {
  const text = String(value || "");
  if (!text) return "";
  if (text.length <= 4) return "****";
  return `${"*".repeat(Math.max(4, text.length - 4))}${text.slice(-4)}`;
}

function envText(values) {
  const lines = [
    "# Generated by Pritha setup. Do not commit this file.",
    `TECHSCOPE_ROOT=${values.TECHSCOPE_ROOT || ROOT}`,
  ];
  for (const [key, value] of Object.entries(values)) {
    if (key === "TECHSCOPE_ROOT") continue;
    if (value !== undefined && value !== null && String(value) !== "") lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function writePrivateFileAtomic(filePath, content) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const previous = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  if (previous === content) return { changed: false, backup: null };
  let backup = null;
  if (previous !== null) {
    backup = `${filePath}.bak`;
    renameSync(filePath, backup);
    chmodSync(backup, 0o600);
  }
  const tempPath = `${filePath}.tmp`;
  writeFileSync(tempPath, content, { mode: 0o600 });
  chmodSync(tempPath, 0o600);
  renameSync(tempPath, filePath);
  chmodSync(filePath, 0o600);
  return { changed: true, backup };
}

function writeJsonAtomic(filePath, payload) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const content = `${JSON.stringify(payload, null, 2)}\n`;
  const previous = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  if (previous === content) return { changed: false };
  const tempPath = `${filePath}.tmp`;
  writeFileSync(tempPath, content);
  renameSync(tempPath, filePath);
  return { changed: true };
}

function defaultConfig() {
  return {
    interfaces: {
      codex: true,
      web: false,
      telegram: false,
      realtime: false,
      obsidian: false,
    },
    web: {
      host: "127.0.0.1",
      port: "3000",
    },
    telegram: {},
    realtime: {
      mode: "always-on",
      confirmedCostPrivacy: false,
    },
    obsidian: {
      vaultPath: ROOT,
    },
    firstAgent: {
      mode: "ask-later",
    },
    qualityGate: true,
  };
}

function mergeConfig(config) {
  const base = defaultConfig();
  return {
    ...base,
    ...config,
    interfaces: { ...base.interfaces, ...(config.interfaces || {}) },
    web: { ...base.web, ...(config.web || {}) },
    telegram: { ...base.telegram, ...(config.telegram || {}) },
    realtime: { ...base.realtime, ...(config.realtime || {}) },
    obsidian: { ...base.obsidian, ...(config.obsidian || {}) },
  };
}

async function interactiveConfig() {
  const config = defaultConfig();
  const rl = createInterface({ input, output });
  try {
    console.log("Pritha setup: minimal Codex-only configuration is the default.");
    const web = (await rl.question("Enable Web UI? [y/N] ")).trim().toLowerCase();
    config.interfaces.web = web === "y" || web === "yes";
    const telegram = (await rl.question("Enable Telegram connector? [y/N] ")).trim().toLowerCase();
    config.interfaces.telegram = telegram === "y" || telegram === "yes";
    const realtime = (await rl.question("Enable Realtime-2 voice? Cost/privacy warning applies. [y/N] ")).trim().toLowerCase();
    config.interfaces.realtime = realtime === "y" || realtime === "yes";
    if (config.interfaces.realtime) {
      console.log("Warning: always-on realtime can keep the microphone open and may continue billing during silence.");
      const confirm = (await rl.question("Continue with realtime always-on? [yes/switch-to-ptt/skip] ")).trim().toLowerCase();
      if (confirm === "skip") config.interfaces.realtime = false;
      if (confirm === "switch-to-ptt") config.realtime.mode = "push-to-talk";
      config.realtime.confirmedCostPrivacy = config.interfaces.realtime;
    }
    const obsidian = (await rl.question("Enable Obsidian vault notes? [y/N] ")).trim().toLowerCase();
    config.interfaces.obsidian = obsidian === "y" || obsidian === "yes";
  } finally {
    rl.close();
  }
  return config;
}

function connectorStatuses(config) {
  const statuses = {
    codex: { status: "configured", detail: "Codex dialog is the default interface." },
    web: { status: config.interfaces.web ? "configured" : "skipped", detail: config.interfaces.web ? `${config.web.host}:${config.web.port}` : "not selected" },
    telegram: { status: config.interfaces.telegram ? "pending" : "skipped", detail: config.interfaces.telegram ? "token validation is non-blocking" : "not selected" },
    realtime: {
      status: config.interfaces.realtime ? (config.realtime.confirmedCostPrivacy ? "configured" : "pending-auth") : "skipped",
      detail: config.interfaces.realtime ? `mode=${config.realtime.mode}` : "not selected",
    },
    obsidian: { status: config.interfaces.obsidian ? "configured" : "skipped", detail: config.interfaces.obsidian ? config.obsidian.vaultPath : "not selected" },
    tailscale: { status: "skipped", detail: "manual Tailscale setup only in v0.1" },
    codexCli: { status: "skipped", detail: "not required for minimal setup" },
    firstAgent: { status: "pending", detail: config.firstAgent?.mode || "ask-later" },
  };
  return statuses;
}

function buildEnv(config) {
  const values = { TECHSCOPE_ROOT: ROOT };
  if (config.interfaces.web) {
    values.HOST = config.web.host;
    values.PORT = config.web.port;
  }
  if (config.interfaces.telegram) {
    values.TECHSCOPE_TELEGRAM_BOT_TOKEN = config.telegram.token || "";
    values.TECHSCOPE_TELEGRAM_ALLOWED_USER_IDS = config.telegram.allowedUserIds || "";
  }
  if (config.interfaces.realtime && config.realtime.openaiApiKey) {
    values.OPENAI_API_KEY = config.realtime.openaiApiKey;
  }
  return values;
}

function statePayload(config, envWrite, quality, statusOverride = null) {
  const sections = connectorStatuses(config);
  sections.environment = { status: "configured", detail: "env-doctor executed before quality gate" };
  sections.secrets = {
    status: envWrite.changed ? "configured" : "configured-externally",
    detail: envWrite.backup ? `backup created: ${safeRelative(envWrite.backup)}` : "no backup needed",
  };
  sections.qualityGate = { status: quality.ok ? "configured" : "failed", detail: quality.ok ? "pass" : "completed with warnings" };
  return {
    schema: "techscope-setup-state-v1",
    version: SETUP_VERSION,
    status: statusOverride || (quality.ok ? "completed" : "completed-with-warnings"),
    updated: new Date().toISOString(),
    root: ROOT,
    interfaces: config.interfaces,
    sections,
    warnings: quality.ok ? [] : [
      "Quality gate returned red. Run `node scripts/self-test.mjs` after fixing the listed checks.",
      quality.stderr || quality.stdout || "quality gate failed",
    ],
    maskedEnv: Object.fromEntries(Object.entries(buildEnv(config)).map(([key, value]) => [key, /TOKEN|KEY|SECRET/i.test(key) ? mask(value) : value])),
  };
}

export async function runSetup(options = {}) {
  const statePath = path.resolve(options.state || DEFAULT_STATE_PATH);
  const envPath = path.resolve(options.env || DEFAULT_ENV_PATH);
  if (options.reset && existsSync(statePath)) renameSync(statePath, `${statePath}.bak`);
  const existing = readJsonIfExists(statePath);
  if (existing?.status === "completed" && !options.reconfigure && !options.reset) {
    if (options.json) console.log(JSON.stringify(existing, null, 2));
    else console.log(`Pritha setup already configured: ${statePath}`);
    return existing;
  }

  const config = options.config
    ? mergeConfig(JSON.parse(readFileSync(path.resolve(options.config), "utf8")))
    : options["non-interactive"]
      ? defaultConfig()
      : await interactiveConfig();

  const envWrite = writePrivateFileAtomic(envPath, envText(buildEnv(config)));
  const skipQuality = options["skip-quality"] || config.qualityGate === false;
  const quality = skipQuality ? { ok: true, stdout: "skipped", stderr: "" } : run("node", ["scripts/quality-gate.mjs"]);
  const state = statePayload(config, envWrite, quality);
  writeJsonAtomic(statePath, state);

  if (options.json) {
    console.log(JSON.stringify(state, null, 2));
  } else {
    console.log(`Pritha setup status: ${state.status}`);
    console.log(`State: ${statePath}`);
    console.log(`Env: ${envPath}`);
    if (!quality.ok) {
      console.log("Completed with warnings:");
      for (const warning of state.warnings) console.log(`- ${warning}`);
    }
  }
  return state;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    console.log(`Usage:
  node scripts/setup.mjs
  node scripts/setup.mjs --non-interactive --config tests/fixtures/setup-minimal.json
  node scripts/setup.mjs --reconfigure realtime
  node scripts/setup.mjs --reset
  node scripts/setup.mjs --state <path> --env <path>`);
    return;
  }
  await runSetup(options);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
